### ISSUE TITLE
WebController doesn't compile

### ISSUE THREAD

**Issue by simasch** [tschuehly/svc-ui#1]
In the master branch I get this compile error

```
/Users/simon/Workspace/frameworks/svc-ui/src/main/java/de/tschuehly/svc/ui/WebController.java:44: error: method renderWithData in class ContentStrategy cannot be applied to given types;
    return contentStrategy.renderWithData(
                          ^
  required: Content<T#1>,T#1
  found:    Box<Task>,User
  reason: inference variable T#2 has incompatible bounds
    equality constraints: Task
    lower bounds: User
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>renderWithData(Content<T#1>,T#1)
    T#2 extends Object declared in class Box
```

**Comment by tschuehly** [comment]
That's actually a feature™! 
I was exploring the idea of type safety at compile time: https://twitter.com/tschuehly/status/1756657584990208462
As the TaskDetails is of type Content<Task> a Task object needs to be passed as data.
The compile error is expected
![image](https://github.com/tschuehly/svc-ui/assets/33346637/243f3b77-dbb8-44b4-8c84-c9f2bf679472)

The current problem I'm facing is that  you can just use a raw type and the error is hidden.
I thought about disallowing raw types with javac -Xlint somehow but I not gotten around it:
![image](https://github.com/tschuehly/svc-ui/assets/33346637/9b85c5e7-6bf2-49c0-a576-cea644f1e033)

**Comment by simasch** [comment]
Got it!
